-- Supabase migration: student_progress table
-- Run this in Supabase SQL Editor: https://btrsgwkwiucuoittshop.supabase.com

CREATE TABLE IF NOT EXISTS public.student_progress (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_name TEXT NOT NULL,
    progress JSONB DEFAULT '{}'::jsonb,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Unique constraint on student_name
CREATE UNIQUE INDEX IF NOT EXISTS idx_student_progress_name 
ON public.student_progress (student_name);

-- Enable RLS
ALTER TABLE public.student_progress ENABLE ROW LEVEL SECURITY;

-- Allow anon to read/write (educational app, no sensitive data)
CREATE POLICY "anon_all" ON public.student_progress
    FOR ALL TO anon USING (true) WITH CHECK (true);

-- Grant permissions
GRANT ALL ON public.student_progress TO anon, authenticated;
GRANT USAGE ON SCHEMA public TO anon, authenticated;
